// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorLiveMentor.Models;

#nullable disable

namespace TutorLiveMentor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210100141_AddSuperAdminMultiDepartmentSupport")]
    partial class AddSuperAdminMultiDepartmentSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TutorLiveMentor.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "CSEDS",
                            Email = "cseds@rgmcet.edu.in",
                            Password = "admin123"
                        });
                });

            modelBuilder.Entity("TutorLiveMentor.Models.AssignedSubject", b =>
                {
                    b.Property<int>("AssignedSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignedSubjectId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("AssignedSubjectId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AssignedSubjects");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ActionPerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SuperAdminId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("SuperAdminId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<bool>("AllowFacultyAssignment")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowStudentRegistration")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSubjectSelection")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HeadOfDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadOfDepartmentEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalFaculty")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubjects")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            AllowFacultyAssignment = true,
                            AllowStudentRegistration = true,
                            AllowSubjectSelection = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "CSEDS",
                            DepartmentName = "Computer Science and Engineering (Data Science)",
                            Description = "Department of Computer Science and Engineering with specialization in Data Science",
                            HeadOfDepartment = "",
                            HeadOfDepartmentEmail = "",
                            IsActive = true,
                            TotalFaculty = 0,
                            TotalStudents = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            DepartmentId = 2,
                            AllowFacultyAssignment = true,
                            AllowStudentRegistration = true,
                            AllowSubjectSelection = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "CSE",
                            DepartmentName = "Computer Science and Engineering",
                            Description = "Department of Computer Science and Engineering",
                            HeadOfDepartment = "",
                            HeadOfDepartmentEmail = "",
                            IsActive = true,
                            TotalFaculty = 0,
                            TotalStudents = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            DepartmentId = 3,
                            AllowFacultyAssignment = true,
                            AllowStudentRegistration = true,
                            AllowSubjectSelection = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "ECE",
                            DepartmentName = "Electronics and Communication Engineering",
                            Description = "Department of Electronics and Communication Engineering",
                            HeadOfDepartment = "",
                            HeadOfDepartmentEmail = "",
                            IsActive = true,
                            TotalFaculty = 0,
                            TotalStudents = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            DepartmentId = 4,
                            AllowFacultyAssignment = true,
                            AllowStudentRegistration = true,
                            AllowSubjectSelection = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "MECH",
                            DepartmentName = "Mechanical Engineering",
                            Description = "Department of Mechanical Engineering",
                            HeadOfDepartment = "",
                            HeadOfDepartmentEmail = "",
                            IsActive = true,
                            TotalFaculty = 0,
                            TotalStudents = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            DepartmentId = 5,
                            AllowFacultyAssignment = true,
                            AllowStudentRegistration = true,
                            AllowSubjectSelection = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "CIVIL",
                            DepartmentName = "Civil Engineering",
                            Description = "Department of Civil Engineering",
                            HeadOfDepartment = "",
                            HeadOfDepartmentEmail = "",
                            IsActive = true,
                            TotalFaculty = 0,
                            TotalStudents = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            DepartmentId = 6,
                            AllowFacultyAssignment = true,
                            AllowStudentRegistration = true,
                            AllowSubjectSelection = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "EEE",
                            DepartmentName = "Electrical and Electronics Engineering",
                            Description = "Department of Electrical and Electronics Engineering",
                            HeadOfDepartment = "",
                            HeadOfDepartmentEmail = "",
                            IsActive = true,
                            TotalFaculty = 0,
                            TotalStudents = 0,
                            TotalSubjects = 0
                        });
                });

            modelBuilder.Entity("TutorLiveMentor.Models.DepartmentAdmin", b =>
                {
                    b.Property<int>("DepartmentAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentAdminId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CanManageFaculty")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageSchedules")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageStudents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageSubjects")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentAdminId");

                    b.HasIndex("AdminId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentAdmins");

                    b.HasData(
                        new
                        {
                            DepartmentAdminId = 1,
                            AdminId = 1,
                            AssignedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CanManageFaculty = true,
                            CanManageSchedules = true,
                            CanManageStudents = true,
                            CanManageSubjects = true,
                            CanViewReports = true,
                            DepartmentId = 1
                        });
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.FacultySelectionSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisabledMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseSchedule")
                        .HasColumnType("bit");

                    b.HasKey("ScheduleId");

                    b.ToTable("FacultySelectionSchedules");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegdNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SelectedSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.StudentEnrollment", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignedSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "AssignedSubjectId");

                    b.HasIndex("AssignedSubjectId");

                    b.ToTable("StudentEnrollments");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxEnrollments")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SemesterEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SemesterStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.SuperAdmin", b =>
                {
                    b.Property<int>("SuperAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperAdminId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SuperAdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SuperAdmins");

                    b.HasData(
                        new
                        {
                            SuperAdminId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "superadmin@rgmcet.edu.in",
                            IsActive = true,
                            Name = "System Administrator",
                            Password = "Super@123",
                            PhoneNumber = "9876543210",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("TutorLiveMentor.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBySuperAdminId")
                        .HasColumnType("int");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.AssignedSubject", b =>
                {
                    b.HasOne("TutorLiveMentor.Models.Faculty", "Faculty")
                        .WithMany("AssignedSubjects")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorLiveMentor.Models.Subject", "Subject")
                        .WithMany("AssignedSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.AuditLog", b =>
                {
                    b.HasOne("TutorLiveMentor.Models.SuperAdmin", "SuperAdmin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SuperAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SuperAdmin");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.DepartmentAdmin", b =>
                {
                    b.HasOne("TutorLiveMentor.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorLiveMentor.Models.Department", "Department")
                        .WithMany("DepartmentAdmins")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.StudentEnrollment", b =>
                {
                    b.HasOne("TutorLiveMentor.Models.AssignedSubject", "AssignedSubject")
                        .WithMany("Enrollments")
                        .HasForeignKey("AssignedSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorLiveMentor.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSubject");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.AssignedSubject", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Department", b =>
                {
                    b.Navigation("DepartmentAdmins");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Faculty", b =>
                {
                    b.Navigation("AssignedSubjects");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.Subject", b =>
                {
                    b.Navigation("AssignedSubjects");
                });

            modelBuilder.Entity("TutorLiveMentor.Models.SuperAdmin", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
